### ISSUE TITLE
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLCanvasElement or HTMLImageElement or HTMLVideoElement or ImageBitmap or OffscreenCanvas or SVGImageElement or VideoFrame)'.

### ISSUE THREAD

**Issue by Aanko** [czx-lab/cinema-seats#1]
下载运行报以下错误

<img width="1354" alt="image" src="https://github.com/czx-lab/cinema-seats/assets/28836989/0a56e9df-2c91-4f3a-8702-b45dd2451179">

**Comment by czx-lab** [comment]
> 下载运行报以下错误
> 
> <img alt="image" width="1354" src="https://private-user-images.githubusercontent.com/28836989/322365700-0a56e9df-2c91-4f3a-8702-b45dd2451179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjA4NzMsIm5iZiI6MTcxMzE2MDU3MywicGF0aCI6Ii8yODgzNjk4OS8zMjIzNjU3MDAtMGE1NmU5ZGYtMmM5MS00ZjNhLTg3MDItYjQ1ZGQyNDUxMTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA1NTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZjRkNmRlMDMxYjYxOWExMDA1ODU5YjEwYjk0MGU0NTg3YmMzZTU1ZjcyNjk1MGY3MjIzOWJhZWQ2Njk4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QYeULMvJbWosu6e3tbx-9M439VN7wn_TcIGJRvuj2fg">

这个没有维护了，报错是因为参数错误，把参数`sold`改成数组
![image](https://github.com/czx-lab/cinema-seats/assets/28135732/412d3f83-e8f4-423f-925a-1136d7d1652d)
